import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavbar from "@/components/BottomNavbar";
import supabaseServer from "@/lib/supabase/server"; // ✅ corrected

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const supabase = await supabaseServer(); // ✅ corrected

  // Get logged-in user
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // Get profile ID
  let profileId = "";
  if (user) {
    const { data: profile } = await supabase
      .from("profiles")
      .select("id")
      .eq("id", user.id)
      .single();

    profileId = profile?.id ?? "";
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased pb-24`}>
        {children}

        {/* Sticky bottom navbar */}
        {profileId && <BottomNavbar profileId={profileId} />}
      </body>
    </html>
  );
}
